// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type DMCChannelGlobalRegister uint8

func (D *DMCChannelGlobalRegister) IRQEnable() bool {
	const bit = 1 << 7
	return *D&bit == bit
}

func (D *DMCChannelGlobalRegister) SetIRQEnable(value bool) {
	const bit = uint8(1) << 7
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*D = DMCChannelGlobalRegister((uint8(*D) & ^bit) | valueInt<<7)
}

func (D *DMCChannelGlobalRegister) Loop() bool {
	const bit = 1 << 6
	return *D&bit == bit
}

func (D *DMCChannelGlobalRegister) SetLoop(value bool) {
	const bit = uint8(1) << 6
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*D = DMCChannelGlobalRegister((uint8(*D) & ^bit) | valueInt<<6)
}

func (D *DMCChannelGlobalRegister) FrequencyIndex() uint8 {
	return uint8((*D >> 0) & 0xf)
}

func (D *DMCChannelGlobalRegister) SetFrequencyIndex(value uint8) {
	const mask = uint8(((1 << 4) - 1) << 0)
	*D = DMCChannelGlobalRegister((uint8(*D) & ^mask) | uint8(value)<<0)
}
