// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type DMCChannelSampleAddressRegister uint8

func (D *DMCChannelSampleAddressRegister) SampleAddress() uint8 {
	return uint8((*D >> 0) & 0xff)
}

func (D *DMCChannelSampleAddressRegister) SetSampleAddress(value uint8) {
	const mask = uint8(((1 << 8) - 1) << 0)
	*D = DMCChannelSampleAddressRegister((uint8(*D) & ^mask) | uint8(value)<<0)
}
