// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type DMCChannelDirectLoadRegister uint8

func (D *DMCChannelDirectLoadRegister) DirectLoad() uint8 {
	return uint8((*D >> 0) & 0x7f)
}

func (D *DMCChannelDirectLoadRegister) SetDirectLoad(value uint8) {
	const mask = uint8(((1 << 7) - 1) << 0)
	*D = DMCChannelDirectLoadRegister((uint8(*D) & ^mask) | uint8(value)<<0)
}
