// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type NoiseChannelGlobalRegister uint8

func (N *NoiseChannelGlobalRegister) LoopEnvelope() bool {
	const bit = 1 << 5
	return *N&bit == bit
}

func (N *NoiseChannelGlobalRegister) SetLoopEnvelope(value bool) {
	const bit = uint8(1) << 5
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*N = NoiseChannelGlobalRegister((uint8(*N) & ^bit) | valueInt<<5)
}

func (N *NoiseChannelGlobalRegister) ConstantVolume() bool {
	const bit = 1 << 4
	return *N&bit == bit
}

func (N *NoiseChannelGlobalRegister) SetConstantVolume(value bool) {
	const bit = uint8(1) << 4
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*N = NoiseChannelGlobalRegister((uint8(*N) & ^bit) | valueInt<<4)
}

func (N *NoiseChannelGlobalRegister) EnvelopePeriod() uint8 {
	return uint8((*N >> 0) & 0xf)
}

func (N *NoiseChannelGlobalRegister) SetEnvelopePeriod(value uint8) {
	const mask = uint8(((1 << 4) - 1) << 0)
	*N = NoiseChannelGlobalRegister((uint8(*N) & ^mask) | uint8(value)<<0)
}
