// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type NoiseChannelLengthRegister uint8

func (N *NoiseChannelLengthRegister) LengthCounterLoad() uint8 {
	return uint8((*N >> 3) & 0x1f)
}

func (N *NoiseChannelLengthRegister) SetLengthCounterLoad(value uint8) {
	const mask = uint8(((1 << 5) - 1) << 3)
	*N = NoiseChannelLengthRegister((uint8(*N) & ^mask) | uint8(value)<<3)
}
