// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type NoiseChannelPeriodRegister uint8

func (N *NoiseChannelPeriodRegister) Loop() bool {
	const bit = 1 << 7
	return *N&bit == bit
}

func (N *NoiseChannelPeriodRegister) SetLoop(value bool) {
	const bit = uint8(1) << 7
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*N = NoiseChannelPeriodRegister((uint8(*N) & ^bit) | valueInt<<7)
}

func (N *NoiseChannelPeriodRegister) Period() uint8 {
	return uint8((*N >> 0) & 0xf)
}

func (N *NoiseChannelPeriodRegister) SetPeriod(value uint8) {
	const mask = uint8(((1 << 4) - 1) << 0)
	*N = NoiseChannelPeriodRegister((uint8(*N) & ^mask) | uint8(value)<<0)
}
