// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type PulseChannelTimerLowRegister uint8

func (P *PulseChannelTimerLowRegister) TimerLow() uint8 {
	return uint8((*P >> 0) & 0xff)
}

func (P *PulseChannelTimerLowRegister) SetTimerLow(value uint8) {
	const mask = uint8(((1 << 8) - 1) << 0)
	*P = PulseChannelTimerLowRegister((uint8(*P) & ^mask) | uint8(value)<<0)
}
