// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type PulseChannelTimerHighRegister uint8

func (P *PulseChannelTimerHighRegister) LengthCounterLoad() uint8 {
	return uint8((*P >> 3) & 0x1f)
}

func (P *PulseChannelTimerHighRegister) SetLengthCounterLoad(value uint8) {
	const mask = uint8(((1 << 5) - 1) << 3)
	*P = PulseChannelTimerHighRegister((uint8(*P) & ^mask) | uint8(value)<<3)
}

func (P *PulseChannelTimerHighRegister) TimerHigh() uint8 {
	return uint8((*P >> 0) & 0x7)
}

func (P *PulseChannelTimerHighRegister) SetTimerHigh(value uint8) {
	const mask = uint8(((1 << 3) - 1) << 0)
	*P = PulseChannelTimerHighRegister((uint8(*P) & ^mask) | uint8(value)<<0)
}
