// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type PulseChannelGlobalRegister uint8

func (P *PulseChannelGlobalRegister) Duty() uint8 {
	return uint8((*P >> 6) & 0x3)
}

func (P *PulseChannelGlobalRegister) SetDuty(value uint8) {
	const mask = uint8(((1 << 2) - 1) << 6)
	*P = PulseChannelGlobalRegister((uint8(*P) & ^mask) | uint8(value)<<6)
}

func (P *PulseChannelGlobalRegister) LoopEnvelope() bool {
	const bit = 1 << 5
	return *P&bit == bit
}

func (P *PulseChannelGlobalRegister) SetLoopEnvelope(value bool) {
	const bit = uint8(1) << 5
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*P = PulseChannelGlobalRegister((uint8(*P) & ^bit) | valueInt<<5)
}

func (P *PulseChannelGlobalRegister) ConstantVolume() bool {
	const bit = 1 << 4
	return *P&bit == bit
}

func (P *PulseChannelGlobalRegister) SetConstantVolume(value bool) {
	const bit = uint8(1) << 4
	valueInt := uint8(0)
	if value {
		valueInt = 1
	}

	*P = PulseChannelGlobalRegister((uint8(*P) & ^bit) | valueInt<<4)
}

func (P *PulseChannelGlobalRegister) EnvelopePeriod() uint8 {
	return uint8((*P >> 0) & 0xf)
}

func (P *PulseChannelGlobalRegister) SetEnvelopePeriod(value uint8) {
	const mask = uint8(((1 << 4) - 1) << 0)
	*P = PulseChannelGlobalRegister((uint8(*P) & ^mask) | uint8(value)<<0)
}
