// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type TriangleChannelTimerLowRegister uint8

func (T *TriangleChannelTimerLowRegister) TimerLow() uint8 {
	return uint8((*T >> 0) & 0xff)
}

func (T *TriangleChannelTimerLowRegister) SetTimerLow(value uint8) {
	const mask = uint8(((1 << 8) - 1) << 0)
	*T = TriangleChannelTimerLowRegister((uint8(*T) & ^mask) | uint8(value)<<0)
}
