// Code generated by running "go generate" in github.com/exp625/gones. DO NOT EDIT.

package apu

type TriangleChannelTimerHighRegister uint8

func (T *TriangleChannelTimerHighRegister) LengthCounterLoad() uint8 {
	return uint8((*T >> 3) & 0x1f)
}

func (T *TriangleChannelTimerHighRegister) SetLengthCounterLoad(value uint8) {
	const mask = uint8(((1 << 5) - 1) << 3)
	*T = TriangleChannelTimerHighRegister((uint8(*T) & ^mask) | uint8(value)<<3)
}

func (T *TriangleChannelTimerHighRegister) TimerHigh() uint8 {
	return uint8((*T >> 0) & 0x7)
}

func (T *TriangleChannelTimerHighRegister) SetTimerHigh(value uint8) {
	const mask = uint8(((1 << 3) - 1) << 0)
	*T = TriangleChannelTimerHighRegister((uint8(*T) & ^mask) | uint8(value)<<0)
}
